/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}', './shared/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        inverseSurface: '#e2e2eb',
        error: '#ffb4ab',
        onPrimaryFixed: '#001f24',
        surface: '#111319',
        secondaryFixed: '#dbe1ff',
        primaryFixed: '#9cf0ff',
        onTertiaryContainer: '#006645',
        surfaceContainerLow: '#191b22',
        tertiaryContainer: '#5be9ad',
        onTertiaryFixed: '#002113',
        onSecondaryFixed: '#00174b',
        surfaceVariant: '#33343b',
        onBackground: '#e2e2eb',
        primaryFixedDim: '#00daf3',
        inversePrimary: '#006875',
        tertiary: '#a8ffd2',
        onPrimaryContainer: '#00626e',
        primaryContainer: '#00e5ff',
        onTertiary: '#003824',
        tertiaryFixedDim: '#4edea3',
        inverseOnSurface: '#2e3037',
        onPrimaryFixedVariant: '#004f58',
        surfaceContainerHigh: '#282a30',
        secondary: '#b4c5ff',
        onSurfaceVariant: '#bac9cc',
        onSecondaryContainer: '#cdd7ff',
        surfaceContainer: '#1e1f26',
        errorContainer: '#93000a',
        surfaceBright: '#373940',
        onErrorContainer: '#ffdad6',
        onError: '#690005',
        secondaryFixedDim: '#b4c5ff',
        tertiaryFixed: '#6ffbbe',
        onPrimary: '#00363d',
        surfaceDim: '#111319',
        onTertiaryFixedVariant: '#005236',
        onSecondary: '#002a78',
        surfaceContainerLowest: '#0c0e14',
        surfaceContainerHighest: '#33343b',
        primary: '#c3f5ff',
        outlineVariant: '#3b494c',
        outline: '#849396',
        onSecondaryFixedVariant: '#003ea8',
        surfaceTint: '#00daf3',
        background: '#111319',
        danger: '#ef4444',
        warn: '#f59e0b',
      },
      fontFamily: {
        display: ['Inter', 'Source Han Sans SC', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        body: ['Inter', 'Source Han Sans SC', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '0.5rem',
        'gutter-md': '0.75rem',
        margin: '0.75rem',
        'margin-lg': '1rem',
        'space-xs': '0.125rem',
        'space-sm': '0.25rem',
        'space-md': '0.5rem',
        'space-lg': '0.75rem',
        'space-xl': '1rem',
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
}
